services:
  mysql:
    image: mysql:latest
    # restart: always
    ports:
      - "3307:3306"  # Correct indentation for portshttp://localhost:8089/


  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"

  myapp:
    image: gorm-app:latest
    build: .
    ports:
      - "8082:8082"  # Correct indentation for ports
    depends_on:
      - mysql
    links:
      - redis

  
    

  